Downloads/ADSI-SistemaSolar-Airbnb-master/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'mensajes/index'
  get 'arrendatario/index'

  get 'arrendador/index'

  get 'home/index'
  get 'properties/index'
  get 'properties/new'
  get 'properties/information'

   get 'subir_casa/new'
   get 'subir_casa/index'

	resources :properties
  resources :searches
	
	#root 'properties#index'
	root 'home#index'
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/models/has_service.rb
class HasService < ApplicationRecord
  belongs_to :property
  belongs_to :service
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/models/image.rb
class Image < ApplicationRecord
  belongs_to :property

  has_attached_file :imagen, styles: {thumb:"320x300"}
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/models/property.rb
class Property < ApplicationRecord
	has_many :images
	has_many :has_services
	has_many :services, through: :has_services

	after_create :set_services

	def services=value
		@services=value 
	end

	def set_services
		@services.each do |serv|
			HasService.create(property_id: self.id, service_id: serv)
		end
	end

	def self.search(search)
		if search
			where(["descripcion LIKE ?", "%#{search}%"])
		else
			all
		end
	end

end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/models/search.rb
class Search < ApplicationRecord

	def search_properties

		properties = Property.all

		properties = properties.where(["descripcion LIKE ?","%#{keywords}%"]) if keywords.present?
		properties = properties.where(["direccion LIKE ?",direccion]) if direccion.present?		
		properties = properties.where(["descripcion LIKE ?",descripcion]) if descripcion.present?
		properties = properties.where(["precio <= ?",maxPrice]) if maxPrice.present?
		properties = properties.where(["servicios LIKE ?",servicios]) if keywords.present?


	end

end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/models/service.rb
class Service < ApplicationRecord
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_services

  def set_services
  	@services=Service.all
  end
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/controllers/arrendador_controller.rb
class ArrendadorController < ApplicationController
  def index
  end
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/controllers/arrendatario_controller.rb
class ArrendatarioController < ApplicationController
  def index
  end
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  def index
  end
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	 
	 #GET /properties
	 def index
  	@properties = Property.search(params[:search])
  end

  #GET /properties/:id
  def show
  	@property = Property.find(params[:id])
  end

  #GET /articles/new
  def new
  	@property = Property.new
  end
  
#POST/properties
  def create 
  	@property =Property.new (property_params)
    @property.services = params[:services]
  	@property.save
  	redirect_to @property
  end
	 
   def property_params
    params.require(:property).permit(:descripcion,:direccion,:precio,:tipo,:services)
   end
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def new
		@search = Search.new
		@categories = Property.uniq.pluck(:tipo)
	end

	def create
		
		@search = Search.create(search_params)
		redirect_to @search

	end

	def show

		@search = Search.find(params[:id])
		
	end

	private

	def search_params

		params.require(:search).permit(:keyword, :direccion, :descripcion, :maxPrice, :tipo, :servicios)
		
	end

end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/controllers/subir_casa_controller.rb
class SubirCasaController < ApplicationController
  
  #GET /properties
  def index
  	@properties = Property.all
  end

  #GET /properties/:id
  def show
  	@property = Property.find(params[:id])
  end

  #GET /articles/new
  def new
  	@property = Property.new
  end
#POST/properties
  def create 
  	@property =Article.new ({ tipo: params[:property][:tipo],
  							direccion: params[:property][:direccion], 
  							precio: params[:property][:precio],
  							descripcion: params[:property][:descripcion]})
  	@property.save
  	redirect_to @property
  end
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/helpers/arrendador_helper.rb
module ArrendadorHelper
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/helpers/arrendatario_helper.rb
module ArrendatarioHelper
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/helpers/home_helper.rb
module HomeHelper
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/helpers/mensajes_helper.rb
module MensajesHelper
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/helpers/searches_helper.rb
module SearchesHelper
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/helpers/subir_casa_helper.rb
module SubirCasaHelper
end

Downloads/ADSI-SistemaSolar-Airbnb-master/app/views/arrendador/index.html.erb
<!DOCTYPE html>
<html>
  <head>
        <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet" type = 'text/css'> 
    <title  class = "colores" > AirbnbITAM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
  	 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a class="navbar-brand" href="/arrendador/index">Airbnb ITAM</a>
                 <a class="navbar-brand" href="/mensajes/index">Mensajes</a>
                 <a class="navbar-brand" href="/properties/index">Mis Propiedades</a>
                 <a class="navbar-brand" href="/properties/new">Subir nueva casa</a>
                 <a class="navbar-brand" href="/home/index">Salir</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>

        <!-- /.container -->
    </nav>
    <div class="container">
    <div class="jumbotron center">
      <p id="sl">NOTIFICACIONES</p>

      <p id="sl">Por el momento no cuentas con ellas</p>

    </div>
    </div>

    <div class="container">
    <%= yield %>
    </div>
    
  </body>
</html>

Downloads/ADSI-SistemaSolar-Airbnb-master/app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
        <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet" type = 'text/css'> 
    <title  class = "colores" > AirbnbITAM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
  	 <!-- Navigation -->
  	<style type="text/css">
	.center{
		margin: 0 auto;
		text-align: center;
	}
	.navbar-inverse .navbar-nav{
		color: white;
	}
	body{
		padding-top: 120px;
		background: url(http://intercambio.itam.mx/Nueva%20Pagina/Alumnos%20Internacionales/fotosyvideos/estacionamiento.jpg);
		background-size: cover;
		background-repeat: no-repeat;
	}
	.jumbotron{
		opacity: 0.8;
	}
	#opaque{
		opacity:1;
	}
		</style>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/home/index">Airbnb ITAM</a>
                <a class="navbar-brand" href="/arrendador/index">Arrendador</a>
                <a class="navbar-brand" href="/arrendatario/index">Arrendatario</a>
                <a class="navbar-brand" href="/users/sign_in">Inicia sesión</a>
                <a class="navbar-brand" href="/users/sign_up"> Regístrate </a>

           <!--     <%=link_to "Cierra Sesion" , destroy_user_session_path, method: :delete%>

           Este es un cerrar sesion que no es relevante para el home
                 -->


            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            </div>
            
                    
                

            
            <div class="col-sm-5 center">
            </div>
            <!-- /.navbar-collapse -->
       </div>
        <!-- /.container -->
    </nav>
    <div class="container">
		<div class="jumbotron center">
			<p id="sl">¡Bienvenid@!</p>

			<p id="sl">Inicia la experiencia AirbnbITAM</p>

		</div>
		</div>
		
		<center><a href="/properties/index" target="_self" /><input type="button" name="boton"  value="Visita nuestra galeria de propiedades"/></center>

		<!-- Botones e iconos -->

    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

Downloads/ADSI-SistemaSolar-Airbnb-master/app/views/properties/index.html.erb
<!-- Page Content -->
<h1>Lista de propiedades</h1>

<%= form_tag properties_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Buscar" %>
<% end %>

<%= link_to "Busqueda Avanzada", new_search_path %>

<!DOCTYPE html>
<html>
  <head>
        <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet" type = 'text/css'> 
    <title  class = "colores" > AirbnbITAM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
     <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a class="navbar-brand" href="/home/index">Airbnb ITAM</a>
                 
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<br></br>
<br></br>
    <div class="container">
                        
            <p class ="colores"> Propiedades </p>
        <div class="row">

            <div class="col-md-9">

                <div class="row">
                    <% @properties.each do |property|%>
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x300" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$<%= property.precio%></h4>
                                <h4><a href="#"><%=link_to property.tipo, property%></a>
                                </h4>
                                <p><%= property.descripcion%></p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">15 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                    <%end%>
                </div>

            </div>

        </div>

    </div>
    
  </body>
</html>
    
    <!-- /.container -->

   

Downloads/ADSI-SistemaSolar-Airbnb-master/app/views/properties/information.html.erb
<!-- Page Content -->

    <div class="container">
                        <p> djasdhsjbs </p>
            <p> djasdhsjbs </p>
            <p class ="colores"> Propiedades </p>
        <div class="row">

            <div class="col-md-9">

                <div class="row">
                	<% @properties.each do |property|%>
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x300" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$<%= property.precio%></h4>
                                <h4><a href="#"><%=link_to property.tipo, property%></a>
                                </h4>
                                <p><%= property.descripcion%></p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">15 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                    <%end%>
                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

   

Downloads/ADSI-SistemaSolar-Airbnb-master/app/views/properties/new.html.erb
<!DOCTYPE html>
<html>
  <head>
        <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet" type = 'text/css'> 
<br></br>
<br></br>
<p class ="tam-default"></p>
<p class ="tam-default"> </p>
<h1 class = "colores">SubirCasa</h1>


<%= form_for(@property) do  |f|%>

<div class="landing-page"><div class="form-appointment"><div class="wpcf7" id="wpcf7-f560-p590-o1"><form action="/landing-page-template-do-not-delete/#wpcf7-f560-p590-o1" method="post" class="wpcf7-form" novalidate="novalidate" _lpchecked="1">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="560">
<input type="hidden" name="_wpcf7_version" value="3.5">
<input type="hidden" name="_wpcf7_locale" value="">
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f560-p590-o1">
<input type="hidden" name="_wpnonce" value="dbb28877d5">
</div>
<div class="group">
<div style="width: 48%; float: left;">

<span class="wpcf7-form-control-wrap email-680"><input type="email" name="email-680" value="" size="45" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" placeholder="Arrendador"></span><br>

<%= f.text_area :direccion, placeholder:  "Dirección"%><br>
<%= f.text_area :descripcion, placeholder:  "Descripción General (sin servicios)"%><br>


<p> Costo 
<%= f.text_field :precio, placeholder:  "Precio deseado"%><br>


</p>
<div style="text-align: center; padding-top: 2em; border-top: 1px solid rgb(153, 202, 129); margin-top: 1em;"><input type="submit" value="Subir Imagen" class="wpcf7-form-control wpcf7-submit"><img class="ajax-loader" src="http://www.professionalaudiologicalservices.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;"></div>

</div>


<div style="width: 48%; float: right;">


<h4>Tipo de propiedad:</h4>
<p><span class="wpcf7-form-control-wrap checkbox-465"><span class="wpcf7-form-control wpcf7-checkbox"><span class="wpcf7-list-item"><label><input type="checkbox" name="checkbox-465[]" value="Cuarto">&nbsp;<span class="wpcf7-list-item-label">Cuarto</span></label></span><span class="wpcf7-list-item"><label><input type="checkbox" name="checkbox-465[]" value="Departamento">&nbsp;<span class="wpcf7-list-item-label">Departamento</span></label></span><span class="wpcf7-list-item"><label><input type="checkbox" name="checkbox-465[]" value="Casa">&nbsp;<span class="wpcf7-list-item-label">Casa</span></label></span><span class="wpcf7-list-item"><label><input type="checkbox" name="checkbox-465[]" value="Otro">&nbsp;<span class="wpcf7-list-item-label">Otro</span></label></span></p>
<%= f.text_field :tipo, placeholder:  "Especifica el otro / Confirma el tipo"%><br><br>

<h4>Fechas de Disponibilidad</h4>
<div class="container">
    <div class="row">
        <div class='col-sm-4'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
    </div>
</div>

<h4>Servicios que ofrece</h4>
<p>

<% @services.each do |service|%>
<div>
<%= check_box_tag "services[]", service.id%><%=service.nombre%>
</div>
<% end%>



<span class="wpcf7-form-control-wrap text-680"><input type="text" name="text-680" value="" size="45" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" placeholder="Especificar"></span><br>

</span></span>

</p>
<div style="text-align: center; padding-top: 2em; border-top: 1px solid rgb(153, 202, 129); margin-top: 1em;"><div>
    <%= f.submit "Subir propiedad" %>
</div>
<%end%>
</div>
  <div class="wpcf7-response-output wpcf7-display-none"></div></form></div></div></div>
</head>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a class="navbar-brand" href="/home/index">AirbnbITAM</a>
               <a class="navbar-brand" href="/arrendador/index">Regresa</a>
                 
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
</html>

Downloads/ADSI-SistemaSolar-Airbnb-master/app/views/properties/show.html.erb
<!DOCTYPE html>
<html>
  <head>
        <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet" type = 'text/css'> 
    <title  class = "colores" > AirbnbITAM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
     <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a class="navbar-brand" href="/home/index">AirbnbITAM</a>
               <a class="navbar-brand" href="/properties/index">Regresa</a>
                 
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div>
    Descripción: <%= @property.descripcion%>
    
</div>
<br></br>
<br></br>
<div>
    Tipo: <%= @property.tipo%>
</div>
<div>
    Precio: $<%= @property.precio%>
</div>
<div>
    Direccion: <%= @property.direccion%>
</div>
<div>
    Servicios: 
</div>
<% @property.services.each do |service|%>
<div>
&nbsp&nbsp&nbsp&nbsp<%= service.nombre%>
</div>
<%end%>
    
  </body>
</html>

Downloads/ADSI-SistemaSolar-Airbnb-master/app/views/subir_casa/index.html.erb
<!DOCTYPE html>
<html>
  <head>
        <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet" type = 'text/css'> 


<h1 class="colores"> Haz click para subir una imagen </h1>

<div>
<span class="wpcf7-form-control-wrap email-680"><input type="Username" name="email-680" value="" size="45" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" placeholder="Username"></span>

</div> <div>
<span class="wpcf7-form-control-wrap email-680"><input type="idPropiedad" name="email-680" value="" size="45" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" placeholder="idPropiedad"></span>

<input type="submit" value="Buscar imagen" class="wpcf7-form-control wpcf7-submit"><img class="ajax-loader" src="http://www.professionalaudiologicalservices.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;">

</div>
<div style="text-align: center; padding-top: 2em; border-top: 1px solid rgb(153, 202, 129); margin-top: 1em;"><input type="submit" value="Subir imagen" class="wpcf7-form-control wpcf7-submit"><img class="ajax-loader" src="http://www.professionalaudiologicalservices.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;"></div>
  <div class="wpcf7-response-output wpcf7-display-none"></div></form></div></div></div>
</head>
</html>